### PR TITLE
Fixed two trivial XCB related bugs.

### LINKED ISSUE #786: Some trivial XCB bugs
Found with clang static code analyzer:

https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/Unix/InputImpl.cpp#L205
```
src/SFML/Window/Unix/InputImpl.cpp:205:31: warning: Value stored to 'result' is never read
        case Mouse::Left:     result = pointer->mask & XCB_BUTTON_MASK_1;
                              ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/SFML/Window/Unix/InputImpl.cpp:206:31: warning: Value stored to 'result' is never read
        case Mouse::Right:    result = pointer->mask & XCB_BUTTON_MASK_3;
                              ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/SFML/Window/Unix/InputImpl.cpp:207:31: warning: Value stored to 'result' is never read
        case Mouse::Middle:   result = pointer->mask & XCB_BUTTON_MASK_2;
                              ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/Unix/WindowImplX11.cpp#L538
```
src/SFML/Window/Unix/WindowImplX11.cpp:538:73: warning: Use of memory after it is freed
        err() << "Failed to set the window's icon: Error code " << (int)errptr->error_code << std::endl;
                                                                        ^~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #786 

Would be nice if someone could test this. @jcowgill maybe? :wink:

### CODE REVIEW

File: src/SFML/Window/Unix/WindowImplX11.cpp [hunk 1]
```diff
@@ -531,11 +531,12 @@ void WindowImplX11::setIcon(unsigned int width, unsigned int height, const Uint8
 
     xcb_generic_error_t* errptr = xcb_request_check(m_connection, cookie);
     bool setWindowIconFailed = (errptr != NULL);
+    uint8_t error_code = errptr->error_code;
```
Comment (jcowgill) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: What happens if `errptr` is NULL?

**Comment by jcowgill** [comment]
The other bits look fine.

File: src/SFML/Window/Unix/WindowImplX11.cpp (hunk 1 above)
Comment (LaurentGomila) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: UB, obviously.

Should be:
```cpp
xcb_generic_error_t* errptr = xcb_request_check(m_connection, cookie);
    bool setWindowIconFailed = (errptr != NULL);
    int error_code = errptr ? errptr->error_code : <the "no error" constant>;
    free(errptr);

    if (error_code != <the "no error" constant>)
    {
        err() << "Failed to set the window's icon: Error code " << error_code << std::endl;
        return;
    }
```

Comment (eXpl0it3r) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: Do we need `the_no_error_constant` since it essentially would just be `NULL`?

Comment (mantognini) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: Having just glanced at the doc for `xcb_request_check` I'm wondering if the following would be better (at least clearer IMO):

```cpp
xcb_generic_error_t* errptr = xcb_request_check(m_connection, cookie);
if (errptr)
{
    err() << "Failed to set the window's icon: Error code " << errptr->error_code << std::endl;
    free(errptr);
    return;
}
```

Comment (eXpl0it3r) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: I was confused above and my comment was useless so I removed it.

According to the docs it either returns an error or `NULL` as such we should always be able to retrieve an `error_code`.

**Comment by eXpl0it3r** [comment]
Change the code the way @mantognini suggested, but added a `static_cast` since an uint8_t would often get printed as character instead of the number.

File: src/SFML/Window/Unix/WindowImplX11.cpp [hunk 2]
```diff
@@ -530,15 +530,13 @@ void WindowImplX11::setIcon(unsigned int width, unsigned int height, const Uint8
...
-    if (setWindowIconFailed)
+    if (errptr)
     {
-        err() << "Failed to set the window's icon: Error code " << (int)errptr->error_code << std::endl;
+        err() << "Failed to set the window's icon: Error code " << static_cast<int>(errptr->error_code) << std::endl;
+        free(errptr);
         return;
     }
-
+
```
Comment (mantognini) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: not really important but there're spaces on this line. =P

Comment (eXpl0it3r) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: Fixed!

File: src/SFML/Window/Unix/InputImpl.cpp [hunk 3]
```diff
@@ -194,24 +194,21 @@ bool InputImpl::isMouseButtonPressed(Mouse::Button button)
 
     // Get pointer mask
     xcb_query_pointer_reply_t* pointer = xcb_query_pointer_reply(connection, xcb_query_pointer(connection, XDefaultRootWindow(display)), NULL);
+    uint16_t mask = pointer->mask;
```
Comment (TankOs) [inline src/SFML/Window/Unix/InputImpl.cpp]: What "bug" does this "fix"? It's the same stuff written in another way.

Comment (LaurentGomila) [inline src/SFML/Window/Unix/InputImpl.cpp]: ```pointer```is no longer accessed after being freed.

Comment (LaurentGomila) [inline src/SFML/Window/Unix/InputImpl.cpp]: Look at the original issue, it is all explained. The "break" statements were missing, and instead of just adding them I suggested a better rewrite.

**Comment by zwookie** [comment]
I tested on Ubuntu 14.04 and the mouse feedback was working again.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.
